#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# https://wiki.archlinux.org/index.php/Xmodmap
# http://askubuntu.com/questions/749660/how-persistently-remap-keys-in-ubuntu-16-04
# http://askubuntu.com/questions/325272/permanent-xmodmap-in-ubuntu-13-04/858272#858272

xmodmap -e "clear lock"
xmodmap -e "clear control"
xmodmap -e "add control = Caps_Lock Control_L Control_R"
xmodmap -e "keycode 66 = Control_L Caps_Lock NoSymbol NoSymbol"
